
# run:
# 	npx promptfoo@latest redteam run



red-team-run:
	echodo npx promptfoo@latest redteam run -c promptfooconfig.yaml
#	npx promptfoo@latest redteam run -c geminock-redteam/promptfooconfig.yaml


report:
	npx promptfoo@latest redteam report
