baseURL: 'https://ricc.rocks/'
title: "Riccardo \U0001F49B Hugo"
theme: zzo
defaultContentLanguage: en
defaultContentLanguageInSubdir: true
hasCJKLanguage: true
summaryLength: 70
buildFuture: true
copyright: '&copy;{year}, Riccardo Carlesso, Some Rights Reserved (github code: https://github.com/palladius/ricc.rocks )'
timeout: 10000
enableEmoji: true
paginate: 13
rssLimit: 100
enableGitInfo: false
googleAnalytics: ''
markup:
  goldmark:
    renderer:
      hardWraps: true
      unsafe: true
      xHTML: true
  highlight:
    codeFences: true
    lineNos: true
    lineNumbersInTable: true
    noClasses: false
  tableOfContents:
    endLevel: 5
    ordered: false
    startLevel: 2
outputs:
  home:
    - HTML
    - RSS
    - SearchIndex
  section:
    - HTML
    - RSS
    - SearchIndex
  taxonomyTerm:
    - HTML
    - RSS
    - SearchIndex
  taxonomy:
    - HTML
    - RSS
    - SearchIndex
outputFormats:
  SearchIndex:
    mediaType: application/json
    baseName: index
    isPlainText: true
    notAlternative: true
taxonomies:
  category: categories
  tag: tags
  series: series
