en:
  title: Riccardo's 💛 Blog
  languageName: English
  weight: 1
  contentdir: content/en
  params:
    footerLinks:
      - name: '📄 Curriculum Vitae (PDF)'
        link: '/cv/ricc-onepager.pdf'
      - name: '💼 Portfolio'
        link: 'https://portfolio-app-272932496670.europe-west1.run.app/about'
      - name: '🐙 GitHub'
        link: 'https://github.com/palladius'
it:
  title: "Riccardo 💛 el mi Blogghe"
  languageName: Italiano
  weight: 2
  contentdir: content/it
  params:
    footerLinks:
      - name: '📄 Curriculum Vitae (PDF)'
        link: '/cv/ricc-onepager-it.pdf'
      - name: '💼 Portfolio'
        link: 'https://portfolio-app-272932496670.europe-west1.run.app/about'
      - name: '🐙 GitHub'
        link: 'https://github.com/palladius'
de:
  title: "Riccardo 💛 Das Blog"
  languageName: Deutsch
  weight: 30
  contentdir: content/de
fr:
  title: "Riccardo 💛 Le Blog"
  languageName: Francais
  weight: 40
  contentdir: content/fr
jp:
  title: "Riccardo 💛 Tsugoi Blog"
  languageName: '日本語 (Japanese)'
  weight: 30
  contentdir: content/jp
