main:
  - identifier: about
    name: 💛About
    url: about
    weight: 1
  - identifier: archive
    name: 🗄️Archive
    url: archive
    weight: 2
    # Keep this for later
  # - identifier: presentation
  #   name: Pt
  #   url: presentation
  #   weight: 3
  - identifier: gallery
    name: 🖼️Gallery
    url: gallery
    weight: 4
  - parent: gallery
    name: Family
    url: gallery/riccardo-family
  - parent: gallery
    name: Sport
    url: gallery/riccardo-sport
  - parent: gallery
    name: Zibaldone
    url: gallery/riccardo-zibaldone
  - parent: gallery
    name: MidJourney
    url: gallery/midjourney
  # - parent: gallery
  #   name: Ricc Work
  #   url: gallery/riccardo-work
    # My wife doesnt like this
  # - parent: gallery
  #   name: Photo
  #   url: gallery/photo
  - identifier: posts
    name: 📪Posts
    url: posts
    weight: 5

  - identifier: ricc_zzo_prod
    name: 🌍Blog
    #url: https://ricc-zzo.netlify.app/
    url: https://ricc.rocks/
    weight: 10

  - identifier: portfolio
    name: 💼Portfolio
    url: https://portfolio-app-272932496670.europe-west1.run.app/about
    weight: 11



    # [Riccardo] This is AMAZING but still nothing to show.
  # - identifier: showcase
  #   name: Showcase
  #   url: showcase
  #   weight: 6

    # [Riccardo] This is AMAZING but still nothing to show.
  # - identifier: publication
  #   name: Pub
  #   url: publication
  #   weight: 7
