main:
  - identifier: about
    name: 💛Chi Sono
    url: about
    weight: 1
  - identifier: archive
    name: 🗄️Archivio
    url: archive
    weight: 2
  - identifier: gallery
    name: 🖼️Galleria
    url: gallery
    weight: 4
  - parent: gallery
    name: Famiglia
    url: gallery/riccardo-family
  - parent: gallery
    name: Sport
    url: gallery/riccardo-sport
  - parent: gallery
    name: Zibaldone
    url: gallery/riccardo-zibaldone
  - parent: gallery
    name: MidJourney
    url: gallery/midjourney

  - identifier: posts
    name: 📪Articoli
    url: posts
    weight: 5

  - identifier: ricc_zzo_prod
    name: 🌍Blog
    url: https://ricc.rocks/
    weight: 10

  - identifier: portfolio
    name: 💼Portfolio
    url: https://portfolio-app-272932496670.europe-west1.run.app/about
    weight: 11

  - identifier: cv
    name: 📄Curriculum (PDF)
    url: /cv/ricc-onepager-it.pdf
    weight: 12
  - parent: cv
    name: 🇮🇹 CV 1-Pagina (IT PDF)
    url: /cv/ricc-onepager-it.pdf
    weight: 1
  - parent: cv
    name: 🇬🇧 CV 1-Page (EN PDF)
    url: /cv/ricc-onepager.pdf
    weight: 2
  - parent: cv
    name: 🇮🇹 CV Completo (IT PDF)
    url: /cv/ricc-cv-it.pdf
    weight: 3
  - parent: cv
    name: 🇬🇧 CV Completo (EN PDF)
    url: /cv/ricc-cv.pdf
    weight: 4
  - parent: cv
    name: 🌐 CV Esteso (HTML)
    url: /cv/
    weight: 5
