[[main]]
  identifier = "about"
  name = "Scopri altro"
  url = "about"
  weight = 1

[[main]]
  identifier = "archive"
  name = "Archivio"
  url = "archive"
  weight = 2

[[main]]
  identifier = "gallery"
  name = "Foto"
  url = "gallery"
  weight = 3

[[main]]
  parent = "gallery"
  name = "fiverr"
  url = "gallery/mine"

[[main]]
  identifier = "posts"
  name = "Articoli"
  url = "posts"
  weight = 4
