
# TODO : import from Makefile..
list:
    @echo "1. just -l. "
    just -l
    @echo "2. More in Makefile"
    cat Makefile

#[group dev]
dev:
	@which hugo >/dev/null 2>&1 && hugo server --disableFastRender || npx -y hugo-bin server --disableFastRender

curl-localhost:
  curl -s http://localhost:1313/
