
run:
	hugo server --disableFastRender

build:
	echo "Riccardo JFYI questo e' quel che Netlify runna.."
	hugo --minify

help:
	echo Read the docs for Hugo and recipe for cocktail.



new-post:
	hugo new posts/my-first-post.md

clean:
	rm -rf resources/_gen/ public/

midjourney-move:
	bin/move-midjourney-pics-to-here.sh

test:
	hugo --minify
