
build:
	echo Riccardo questo e quel che Netlify runna..
	hugo --minify

help:
	echo Read the docs for Hugo and recipe for cocktail.


run:
	hugo server --disableFastRender

new-post:
	hugo new posts/my-first-post.md

clean:
	rm -rf resources/_gen/ public/

midjourney-move:
	bin/move-midjourney-pics-to-here.sh
