
gcp-cheatsheets-copy:
	git clone git@github.com:palladius/gcp-cheatsheets.git gcp-cheatsheets-copy
	cp -R gcp-cheatsheets-copy/cheatsheets/ docs/gcp-cheatsheets-copy/

clean:
	rm -rf gcp-cheatsheets-copy/
