# Change baseurl before deploy
baseurl: "https://hugo-stack.ricc.rocks"
#baseurl: 'https://timely-bombolone-ae5bc6.netlify.app/'
languageCode: "en-us"
paginate: 5
title: "Riccardo 💛 Stack"
# Theme i18n support
# Available values: en, fr, id, ja, ko, pt-br, zh-cn, zh-tw, es, de, nl, it, th, el, uk, ar
DefaultContentLanguage: "en"

# Set hasCJKLanguage to true if DefaultContentLanguage is in [zh-cn ja ko]
# This will make .Summary and .WordCount behave correctly for CJK languages.
hasCJKLanguage: false

# Change it to your Disqus shortname before using
disqusShortname: "disqus_7JS1PTrMOB"

links:
  - title: GitHub
    description: GitHub is the world's largest software development platform.
    website: https://github.com
    image: https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png
  - title: TypeScript
    description: TypeScript is a typed superset of JavaScript that compiles to plain JavaScript.
    website: https://www.typescriptlang.org
    image: ts-logo-128.jpg
