

download: all

all: ananke zzo

gohugo-theme-ananke-copy:
	git clone https://github.com/theNewDynamic/gohugo-theme-ananke/ gohugo-theme-ananke-copy/
# exampleSite:  gohugo-theme-ananke
# 	cp -R gohugo-theme-ananke/exampleSite/ exampleSite/

ananke: gohugo-theme-ananke-copy
	cp -R gohugo-theme-ananke-copy/exampleSite/ ananke/


hugo-theme-zzo-copy:
	git clone https://github.com/zzossig/hugo-theme-zzo hugo-theme-zzo-copy
zzo: hugo-theme-zzo-copy
	cp -R hugo-theme-zzo-copy/exampleSite/ zzo/


