
# alias promptfoo='/usr/local/google/home/ricc/git/py-pvt-gemini-chat-challenge/genai-training/vertex-eval/deepeval/genai-beyond-basics/samples/evaluation/node_modules/.bin/promptfoo'

eval:
	./promptfoo-eval.sh


auth:
	gcloud auth login --update-adc
# --quiet


