

eval:
#	promptfoo eval ; promptfoo view
# this is not ok since i have --- ibn the ptompt!
#	PROMPTFOO_PROMPT_SEPARATOR='---' promptfoo eval ; promptfoo view
	PROMPTFOO_PROMPT_SEPARATOR='-A-A-A-' promptfoo eval ; promptfoo view

# https://www.promptfoo.dev/docs/guides/gemini-vs-gpt/
promptfoo-tests:
	npx promptfoo@latest init promptfoo-tests


