FROM ruby:3.3-alpine

RUN apk add --no-cache build-base

WORKDIR /app

COPY Gemfile ./
RUN bundle config set without 'development test' && bundle install --jobs 4

COPY app.rb config.ru ./

ENV PORT=8080
ENV RACK_ENV=production

EXPOSE 8080

CMD ["bundle", "exec", "puma", "-p", "8080", "-e", "production"]
